spring:
  application:
    name: registry-center
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:store-db;database_to_upper=true

server:
  port: 7000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

springdoc:
  swagger-ui:
    path: /ui